# Generated by Django 3.2.4 on 2021-07-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='redirect_to',
            field=models.CharField(default='https://www.google.com/', max_length=500),
            preserve_default=False,
        ),
    ]
